### PR TITLE
Install script for custom QPDF versions

### PR DESCRIPTION
**Pull request by joesiewert**

### CODE REVIEW

**Review by mlocher — COMMENTED** [review]
What do you think about implementing tests for new packages via `bats` and not extending the `packages.sh` script any longer.

That way we already have less work to do, when we switch package tests to `bats`.

**Review by mlocher — APPROVED** [review]
follow up PR which converts the test required.

**Comment by andyw8** [comment]
Thanks for this, but would it be feasible to cache the compiled binary rather than the download? Otherwise each build runs for an extra 2 minutes to build it.

I'm happy to open a PR do so.

**Comment by andyw8** [comment]
Nevermind, I see it does cache the compiled version too.

**Pull request merged**
