### PR TITLE
Update to Git LFS 2.0.0

### PR DESCRIPTION
**Pull request by mlocher**
See https://github.com/blog/2328-git-lfs-2-0-0-released and https://github.com/git-lfs/git-lfs/releases/tag/v2.0.0 for the release notes.

I'm not sure we can merge this as is, because of the following deprecation.

Maybe we should update the default installation to 1.5.6 and add a warning?

> Deprecations
> 
> Git LFS v2.0.0 also drops support for the legacy API in v0.5.0. If you're still using LFS servers on the old API, you'll have to stick to v1.5.6.

### CODE REVIEW

**Comment by joesiewert** [comment]
Maybe set the default for the script to `1.5.6` like you said, but change the test to run `2.0.0`?

https://github.com/codeship/scripts/blob/master/tests/packages.sh#L21

That way it shouldn't introduce a break for builds using the defaults, but we're making sure the script can install the current version.

**Comment by mlocher** [comment]
I think I'll also add a warning message if users are relying on the default version from the script alerting them that we will update to 2.0.0 in the future.

**Comment by mlocher** [comment]
@joesiewert updated the PR to use 1.5.6 per default and print a warning message and test 2.0.0 and the default version in the test.

Could you review the changes again? 🙇

**Review by joesiewert — APPROVED** [review]
:shipit:

**Pull request merged**
