### PR TITLE
Add option to change MongoDB storage engine

### PR DESCRIPTION
**Pull request by tjokimie**
Add `MONGODB_STORAGE_ENGINE` option for changing MongoDB storage engine.

### CODE REVIEW

**Comment by mlocher** [comment]
Hey @tjokimie, thanks for taking the time to prepare this PR.

If adding the environment variable is the only change, why do we need to modify the script? Wouldn't it work just as well if you set the environment variable outside of the script and then call it. Like in the following snippet:

```shell
export MONGODB_STORAGE_ENGINE="wiredTiger"
\curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/mongodb.sh | bash -s
```

I might be missing something but with the current changes the snippet above should produce the same result without any changes to the script itself.

**Comment by tjokimie** [comment]
@mlocher Sorry, forgot to commit the actual change 😞  

Added the missing `--storageEngine` parameter in https://github.com/codeship/scripts/pull/171/commits/c7406494bdd64480083866b2abb7356ed19c4675.

**Comment by mlocher** [comment]
Nice. I'll take a look and will take this PR as a chance to add some more tests for the script, but this looks good now.

**Comment by tjokimie** [comment]
@mlocher Great, thanks! :+1:

**Comment by mlocher** [comment]
Hey @tjokimie, 

it took a bit longer than expected, but my PR with your changes is finally merged. Thanks again for taking the time to prepare this, we really appreciate the effort that went into this 🙇

**Pull request closed without merging**
