### PR TITLE
Add custom install script for Erlang and Elixir

### PR DESCRIPTION
**Pull request by mlocher**

### CODE REVIEW

**Comment by beanieboi** [comment]
nice ❤️

**Comment by mlocher** [comment]
Tests failed because of #103, I'll rebase and (force) push once that is merged.

**Comment by mlocher** [comment]
Whoops, there are a couple cleanup tasks I need to do with that PR, still references Go in the comments :(

**Comment by mlocher** [comment]
Made the updates to the comments, this PR is ready to go :)

**Comment by krames** [comment]
LGTM 👍

**Pull request merged**
