### PR TITLE
Install and configure Google Cloud SDK

### PR DESCRIPTION
**Pull request by mlocher**
This is a first draft, installation works, but the authentication hasn't been tested yet. To upgrade to a newer version you need to reset the dependency cache on Codeship.

### CODE REVIEW

**Comment by joesiewert** [comment]
Ready for another look @mlocher.

**Comment by mlocher** [comment]
can't approve, as I'm one of the authors :D, looks great though. 

Two things we might want to keep in mind and address in a future PR

* the cached download doesn't expire at the moment
* should we exit with an error code if `${GOOGLE_CLOUD_KEY}` and  `${GOOGLE_CLOUD_PROJECT_ID}` are not set?

@ethangj could you take a look?

**Review by ethangj — APPROVED** [review]
lgtm!

**Comment by mlocher** [comment]
great we finally got the PR #1 shipped (and a little sad it took that long to get it finished). Thanks @joesiewert for taking over!

**Pull request merged**
