### PR TITLE
Checkout git LFS contents when installing

### PR DESCRIPTION
**Pull request by mlocher**
- Make sure to run fetch and checkout files stored via LFS
- Update the default version to 1.3.1

### CODE REVIEW

**Comment by ethangj** [comment]
lgtm, may want an expert opinion though

**Comment by zartux** [comment]
Hey all, what's the best way to use this script in a codeship build? Put it in codeship-steps.yml?

**Comment by mlocher** [comment]
Hey @zartux those scripts are targeted at our Classic infrastructure. While most will work on the Docker platform as well some won't, and unfortunately this is one of those.

I'll forward your feature request regarding support for Git LFS to our product team and and let them know this is an important feature to add.

**Comment by zartux** [comment]
Ah cool, thanks for the update @mlocher

**Pull request merged**
